embed_assets: datauri

javascripts:
  lib:
    - public/javascripts/rails.js
    - public/javascripts/jquery/jquery-1.4.4.min.js
    - public/javascripts/jquery/jquery-ui-1.8.7.custom.min.js
    - public/javascripts/fancybox/jquery.fancybox-1.3.4.js
    - public/javascripts/fancybox/jquery.easing-1.3.pack.js
    - public/javascripts/jquery/flash.js
    - public/javascripts/handlebars/handlebars.js

  healer:
    - public/javascripts/application.js
    - public/lib/schedule.js
    - public/javascripts/lib/jquery.fancybox.overrides.js
    
stylesheets:
  common:
    - public/stylesheets/fancybox/jquery.fancybox-1.3.4.css
    - public/stylesheets/healer/jquery-ui-1.8.7.custom.css
  ie:
    - tmp/stylesheets/compiled/ie.css
  print:
    - tmp/stylesheets/compiled/print.css
  screen:
    - tmp/stylesheets/compiled/screen.css
