anatomy:
  femur_diameters_hip: ["N/A",5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
  femur_diameters_knee: [55,60,65,70,75,80,85]
  femur_head_sizes: ["N/A",22,26,28,30,32,36,40,44]
  femur_lengths: ["N/A",105,110,115,120,125,130,135,140,145,150,155,160,165,170,175,180,185,200,220,240]
  acetabulum_sizes: ["N/A",40,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80]
  neck_lengths: ["N/A",-6,-3,0,3,6,9,12]
  tibia_diameters: [60,65,70,75,80]
  tibia_thicknesses: [10,12,14,16,18,20,22]
  patella_sizes:
    0: "Small"
    1: "Medium"
    2: "Large"
implants:
  prosthesis_types:
    - "bimetric"
    - "calcar"
    - "taperloc"
    - "ranawat socket"
    - "porous socket only"
  surface_options:
    - "Polyethylene"
    - "Ceramic"
    - "Metal"
  tibia_types: ["Metal-backed"]
  knee_types: ["CR","PS","CC","Hinge"]
operation:
  approaches:
    - "Anterior"
    - "Lateral"
    - "Medial"
    - "Posterior"
    - "Dorsal"
    - "Planter"
    - "Lateral Transfibular"
    - "Transtrochanteric"
  ambulatory_orders:
    - "Weight Bearing as Tolerated"
    - "Non-Weight Bearing"
    - "Partial Weight Bearing"
    - "Heel Weight Bearing"
  osteotomy_options:
    - "None"
    - "Trochanteric"
    - "Sub-trochanteric"
    - "Tibial Tubercal Osteotomy"
  anesthsia_types:
    - "spinal"
    - "general"
    - "local"
  peripheral_nerve_block_types:
    - "femoral"
    - "sciatic"
    - "sciatic/femoral"
    - "popliteal"
    - "ankle"
    - "local"
    - "ExParel"
    - "none"
  difficulty_table:
    0: "Routine"
    1: "Moderate"
    2: "Severe"