#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

require "csv"
require "aws/s3"

raise "S3_KEY must be set in ENV" unless ENV['S3_KEY'].present?
raise "S3_SECRET must be set in ENV" unless ENV['S3_SECRET'].present?

AWS::S3::Base.establish_connection!(
  :access_key_id     => ENV['S3_KEY'],
  :secret_access_key => ENV['S3_SECRET']
)

bucket = 'healer-production'
filename = 'opwalk_people.csv'

if AWS::S3::S3Object.exists?("data/#{filename}", bucket)
  csv = AWS::S3::S3Object.find("data/#{filename}", bucket)
  contents = csv.value.split("\r")
  contents.each do |row|
    row_vals = row.split(",")
    next if row_vals[0] == "name"
    name_last = row_vals[0].gsub("\"", "").strip
    name_first = row_vals[1].gsub("\"", "").strip.split(" ")[0]
    role = row_vals[3].present? ? row_vals[3].strip : nil
    email = row_vals[4].present? ? row_vals[4].strip.downcase : nil
    if email.present?
      u = User.new(:email => email, :name_first => name_first, :name_last => name_last)
      u.save if u.valid?
      u.grant_role!(role) if role.present?
    end
  end
else
  raise "File does not exist at #{bucket}:data/#{filename}"
end