#!/bin/sh
mkdir -p public/system/xrays
mkdir -p public/system/patients

# custom script to pull S3 assets for local app sync
echo "Pulling x-ray photos..."
s3cmd get --delete-removed --skip-existing --recursive s3://healer-production/xrays/ public/system/xrays

echo "Pulling patient photos..."
s3cmd get --delete-removed --skip-existing --recursive s3://healer-production/patients/ public/system/patients